### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by mersahin**

### CODE REVIEW

**Comment by harunaltunhr** [comment]
OK

**Comment by mersahin** [comment]
neden ok

**Review by kemaltt — COMMENTED** [review]
ok

**Comment by Osman-Ozturk** [comment]
ok

**Comment by mersahin** [comment]
test

**Comment by mersahin** [comment]
close

**Review by Osman-Ozturk — APPROVED** [review]
ok

**Review by harunaltunhr — APPROVED** [review]
I controlled, eveything is Ok

**Pull request merged**
